### ISSUE TITLE
Console command to clear cache

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#114]
**Describe the solution you'd like**
Add a console command to delete the cache (mem and db).

**Comment by umulmrum** [comment]
Looks mostly good to me. Two things I saw while testing:
- On errors the command still returns "OK". This is caused by the cache implementation itself hiding the error, so we can't improve this here (see https://github.com/chameleon-system/chameleon-system/issues/127).
- If the cache is disabled, the command also returns "OK". By itself this is not a problem, but as the default environment for the console is dev and the cache is disabled by default in dev, it is really easy to miss, so that the cache won't be flushed. @UlrichKu could you add a check for $this->cache->isDisabled() and output an appropriate message if it's disabled? As this is not an error, I would still return 0 though.
