### ISSUE TITLE
Add bundle config for Less generation paths

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#117]
**Describe the solution you'd like**
Less creation and storge should not necessarily happen in the current "outbox/static" shared directory.

It should be configurable (bundle config with (old) default path).

**Comment by umulmrum** [comment]
Some issues found during the test:
- In prod mode the generated CSS file is not hit but CSS is regenerated on each request (using the cache but anyway PHP is called instead of serving the static file). TPkgViewRendererLessCompiler::getLessDirUrlPath() needs to be adjusted to use the configured value. Also the route in src/ViewRendererBundle/Resources/config/routing.yml is defined statically and so cannot reflect the config yet.
- When clearing the file cache from the backend, the generated CSS is not deleted if the path is changed (see MTHeader::clearCacheFiles()).
- In the CMS settings there is a field "Additional files to be deleted when clearing the cache" which by default contains the path to the outbox/static/less/cached directory. I think we should hard-code that files in this path get deleted (using the configured path of course) and add a migration script that removes the path from that field.
- The configured path must always be under the document root as the CSS files are intended to be delivered to clients directly. We should interpret the configured value relative to PATH_WEB to simplify configuration and to avoid user errors (please also add this information to the config value info).
- Also we should add to the config info that all files in the configured directory are deleted on cache clear so that this directory should not contain any other files.

@UlrichKu could you address these issues?

**Comment by umulmrum** [comment]
Had to revert the change because of time constraints - as written in chameleon-system/chameleon-base#64, please make a new proposal that contains changes both from chameleon-system/chameleon-base#56 and chameleon-system/chameleon-base#64
