### ISSUE TITLE
tls mail hosts no longer supported

### ISSUE THREAD

**Issue by rnuernberg** [chameleon-system/chameleon-system#140]
**System behavior before the change**
It was possible to use a tls URL as mail host. Example:  tls://email-smtp.eu-west-1.amazonaws.com:587

**System behavior after the change**
Providing the host this way will attempt to use ://email-smtp.eu-west-1.amazonaws.com:587 as port. No mails can be sent.

**Affected version(s)**
6.2

Note: the mailer class supports setting $mail->SMTPSecure = "tls" (but this is not tested)

**Comment by umulmrum** [comment]
@rnuernberg The problem is located in \TCMSMail::setSmtpHost(). There we split the string into host and port, and for this purpose we split by colon. Your string contains two colons which leads to the error. Maybe we should split by the last colon instead of the first and also check if the second part is numeric. Could you provide a fix?

(on a side note: Could you adjust the ticket summary so that it only contains English language? :-) )

**Comment by rnuernberg** [comment]
@umulmrum that would mean, tls would always require a port. I am not sure if we can make that assumption. To avoid backward compatibility issues I would argue, that we need the user to be able to specify the port as a separate optional parameter. 

If you agree, I can implement a fix.

**Comment by umulmrum** [comment]
I suppose it should be feasible to support all cases with the existing config. But I think it's also perfectly legitimate to add a separate port argument - whatever you prefer :-) (not sure if we even should support both, but we can discuss this later)
