### ISSUE TITLE
Backend: Main menu item order

### ISSUE THREAD

**Issue by umulmrum** [chameleon-system/chameleon-system#155]
**Describe the solution you'd like**
The backend main menu could be improved:
- Category box titles (which boxes exist with which names).
- Move menu items to better-fitting category boxes.
- Rename some menu items.
- Find suited category boxes for navigation, pages, media manager, document manager, which are currently part of the top navigation. They will be part of the regular menu now.
- Improve ordering of main menu items. Keep in mind that this order might be adjustable as part of a perspective (see #156).

Please keep also in mind that the ultimate goal for the main menu is to be displayed as a sidebar with a reduced number of categories for a user (#156). If we manage to find a good distribution of menu items, we should be able to design better default perspectives (and maybe we can then limit the scope of perspectives to category boxes and don't need to hide menu items themselves for perspectives).

Please collect change proposals here in the ticket before we apply them in the official database dump.

**Comment by esono-anja** [comment]
1. I'm still not happy with the wording "Listenfiltereinstellungen". How about "Listenfilter" (List filter). Besides, I would change "Produktauswahl" to "Produktauswahlfilter" (Product selection filter).

2. > "Systemnachrichten / Fehlercodes-Typen" in "Systemnachrichtentypen" statt "Systemnachrichten" umbenannt. Es geht hier um Arten von Nachrichten, nicht um die Nachrichten selbst. (System Messages / Error Code Types" renamed to "System Message Types" instead of "System Messages". These are types of messages, not the messages _themselves.)

This item "System message types" is now missing. Instead, in layout "System messages / error codes" the actual messages themselves are displayed now (which are also displayed under Portals / Website.)

3. In Data exchange we have 2 times "Importe / Exporte ausführen." The second item must be "Importe / Exporte konfigurieren" (in English it is correct).

**Comment by umulmrum** [comment]
1: Changed "Listenfiltereinstellungen" to "Listenfilter" and "Produktauswahl" to "Produktauswahlfilter". I'd keep "Produktlistensortierung" as it would be rather confusing not to write that we're handling products here.

2: Fixed.

3: Fixed.
