### ISSUE TITLE
Cannot open media editor (500)

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#237]
Noticed in #108:

**Describe the bug**
Do as described in #108: click edit on an image in the media editor. There will be a short error popup with "500 internal server error" and nothing else.

**Affected version(s)**
6.2.5.preview

**Technical details**
The local reason for 500: An exception occurred while executing 'SELECT * FROM pkg_cms_credit_check WHERE text_credit_check_pending LIKE ? OR text_credit_check_pending__de LIKE ?' with params ["%cmsmedia="9927eff6-9bfa-0588-057c-6e29b8715fe9%", "%cmsmedia="9927eff6-9bfa-0588-057c-6e29b8715fe9%"]:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'text_credit_check_pending__de' in 'where clause'

This happens when determining the usages of that image (in every text field in the system).

Adding the table column helps.

**Comment by umulmrum** [comment]
The problem is that the migration script of another bundle (unrelated to the Chameleon core) sets the multilingual flag manually before calling TCMSLogChange::FieldChangeMultiLanguageSetting(). The FieldTranslationUtil then thinks there is nothing to do. I changed the behavior so that the setting switch is always done to avoid a BC break.
