### ISSUE TITLE
Backend: Styling MediaMangager

### ISSUE THREAD

**Issue by ckleis** [chameleon-system/chameleon-system#294]
Media Manager:responsive styling and general styling improvements.

This is what it looks like now:
![selection_250](https://user-images.githubusercontent.com/26296728/52107785-0525ef00-25f8-11e9-911e-0ba6557efc43.jpg)

![selection_251](https://user-images.githubusercontent.com/26296728/52107814-225abd80-25f8-11e9-94e2-e2a4bc781230.jpg)

![selection_252](https://user-images.githubusercontent.com/26296728/52107836-37375100-25f8-11e9-9865-96b321e3a483.jpg)

**Comment by esono-anja** [comment]
I like the buttons for flagging the pics. However, i was irritated because in other lists we do not use such buttons, but checkboxes. Moreover, at first, I didn't know what the buttons were for. The question is should we standardise the buttons for flagging the record?
![mm_buttons](https://user-images.githubusercontent.com/15125103/53502659-d6901c80-3aae-11e9-9f33-7154c357a560.png)

**Comment by umulmrum** [comment]
@ckleis AFAIR you did this on purpose - could you explain?

**Comment by ckleis** [comment]
As discussed with Sven and Stefan, the styling of the checkboxes has changed:
![Selection_305](https://user-images.githubusercontent.com/26296728/54187617-49859400-44ae-11e9-9718-95a9b8e156fb.jpg)

**Comment by ckleis** [comment]
The iframe for the cutout (inside the mediaManager) always had the height of its container, but the image was usually larger and the iframe had scrollbars.
Now the iframe gets its own height.

In addition, there was a styling adjustment for the save button.
