### ISSUE TITLE
Backend: Styling document manager

### ISSUE THREAD

**Issue by ckleis** [chameleon-system/chameleon-system#309]
**Describe the solution you'd like**
Now, the document manager looks like this:

![selection_270](https://user-images.githubusercontent.com/26296728/52626290-279af080-2eb3-11e9-9279-e6df862d9342.jpg)

It should be designed like the navigation manager and consider that it can also be called as iframe.

**Comment by ckleis** [comment]
The scrollbars still have to be removed.
It's very confusing by many inline-styles and table styles...

![selection_275](https://user-images.githubusercontent.com/26296728/52641670-ab67d380-2ed9-11e9-873c-5e0da49b9ac2.jpg)

**Comment by esono-anja** [comment]
I'm not sure if everything was implemented (iFrame yes or no?). Are there 2 windows here? Please test yourself.
![docs](https://user-images.githubusercontent.com/15125103/53428738-9c117b80-39eb-11e9-8725-86f775e7e954.png)

**Comment by umulmrum** [comment]
Looks mostly good.

Some findings:
- The context menu appearing on right-click on a folder is still old-fashioned and needs to be styled.
- File type icons are still old-fashioned. Not sure if we have suiting replacements, though.
- In the detail view of a document, the field "Last changed on" isn't displayed correctly. There is a dangling double-quote character at the end, and the German word "Uhr" is also displayed in English (instead of "h").
- And of course the rendering issue @esono-anja found (see the arrow on their screenshot). This appears only to happen in tablet mode.

@ckleis Could you have a look?

**Comment by pixeljunkie** [comment]
- "The context menu" should be replaced in the near future with the new tree.js version, so i would not change here anything, or update right now (8h of work minimum)
- File type icons are generated with a tool, so we have no licence issue and are able to create missing ones with the same style. The icons are used in frontend, too, so please be aware of this.

**Comment by pixeljunkie** [comment]
Possible free new filetype icons based on SVG: https://github.com/dmhendricks/file-icon-vectors/
For the frontend, this would mean a BC break (not a big one, but it would need changes in CSS style names if someone has overwritten the icons).
This icon set may be required via composer.

**Comment by ckleis** [comment]
Icons in context-menu are changed to font-awesome icons and the translation "Uhr" and h is correct now.

**Comment by esono-anja** [comment]
> Some findings:
> * And of course the rendering issue @esono-anja found (see the arrow on their screenshot). This appears only to happen in tablet mode.

It was discussed that this topic should also be postponed.
