### ISSUE TITLE
Add main menu migration helper for non standard bundles and custom menu items

### ISSUE THREAD

**Issue by umulmrum** [chameleon-system/chameleon-system#335]
**Describe the solution you'd like**
During migration to Chameleon 6.3 new sidebar menu items are generated from existing tables and modules. While this works for default items, other menu items, e.g. from 3rd party bundles or the project itself will not be generated. This will be quite annoying during migration, so we should at least add an "other" menu category where these menu items get placed.

**Comment by pixeljunkie** [comment]
Using an "other" menu category to migrate all non standard menu items to the new sidebar menu was not a solution. I added a migration service that allows every bundle to migrate items to the new structure and added a core update that migrates all unhandled items.

**Comment by pixeljunkie** [comment]
Forgot to mention the main reason for the migrator... if you setup a bundle later, the menu items would be missing without a migration update in the bundle because the migration already run before in the core. So every bundle that adds menu items (adds tables, that are accessible via main menu) needs an update call.
