### ISSUE TITLE
Backend: force cache clear for asset files

### ISSUE THREAD

**Issue by pixeljunkie** [chameleon-system/chameleon-system#375]
**Describe the solution you'd like**
Every time we replace backend asset files (CSS/JS) with a new version the user needs to clear the browser cache to prevent caching of old versions.
We should add the release number to these resources to prevent caching

**Possible solution (if any)**
The core uses TGlobalBase::GetStaticURLToWebLib($filepath) for most of the resources so this is the method we could add the version number.
It needs to consider that the filePath may have already a version number.

**Comment by umulmrum** [comment]
I'm afraid we can't use `TGlobalBase::GetStaticURLToWebLib()` - this method can be called without path argument so that it just returns a base path where a relative path can then be appended. So we can't add version information without destroying these use cases (we could do magic with symlinks so the asset version information is part of the path, but that road is heading straight downwards). There are also internal methods that use the method without argument, namely `TGlobalBase::GetPathWebLibrary()` and `TCMSConfig::GetThemeURL()`.

Even if we could change that method, there are still lots of asset paths that are generated in another way, e.g. by calling `TGlobal::GetPathTheme()`. This method does not accept arguments, so we cannot attach version information.

So unless you have a great idea I think there is no solution other than doing massive changes to the asset URL generation.

**Comment by bestform** [comment]
@pixeljunkie are there any new ideas on how to achieve this without rewriting the whole path generation code and braking everything?

**Comment by UlrichKu** [comment]
The issue #557 superseeds this.
