### ISSUE TITLE
Fluttering (switching effect) while showing tables or popups

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#400]
**Describe the bug**
When "displaying things" sometimes theses are shown with a fluttering effect:
the element gets wider and narrower in rapid succession for a second.

This happens for example for the popup when accessing "Navigation" and "Edit a node" or when opening a the "Domains" block in "Portals".

In both cases there is a horizontal scrollbar which shouldn't probably be there.

**Affected version(s)**
6.3

**Comment by ckleis** [comment]
The flutter is the display and hiding of the vertical scrollbar of an iframe. "body.app" inside the iframe is set by coreui to a min-height of 100vh. This leads to problems with the Symfony bar (fixed bottom), which then toggles the vertical scrollbar.
If the min-height is set to 100% instead of 100vh, it works fine.

**Comment by UlrichKu** [comment]
The fix leads to the grey footer line (with the version) not being at the bottom of the browser window anymore (but directly below the content).

**Comment by UlrichKu** [comment]
> The fix leads to the grey footer line (with the version) not being at the bottom of the browser window anymore (but directly below the content).

Corrected

**Comment by esono-anja** [comment]
Seems fixed in 6.3, but does appear in 7.0, if there is a vertical scrollbar (i.e. in lists that can be expanded and collapsed).
