### ISSUE TITLE
Backend: date field: does not close on focus lost

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#509]
**Describe the bug**
Clicking in a date field will open a datetimepicker popup.
Clicking somewhere else will not close it - only clicking in the date field again.

**Affected version(s)**
6.3+

**Technical details**
This in tableEditor.js is responsible:

`    // workaround for tempusdominus bug: https://github.com/tempusdominus/bootstrap-4/issues/123
   
 $('*[data-toggle="datetimepicker"]').removeClass('datetimepicker-input');`

**Comment by JavidShoaei** [comment]
@UlrichKu The "workaround" you mentioned is not really solving anything. Yes, it prevents the error but raises other issues. For example, the popup will not close automatically.

**Comment by UlrichKu** [comment]
Will be solved by removing the workaround introduced with #357 and using a different one (avoid parsing).

**Comment by esono-anja** [comment]
The date popup cannot be closed at all except by reloading the page.

**Comment by esono-anja** [comment]
- 6.3: The popup of the date picker now closes with a click outside the field. However, it does not close with a click on a date entry, but you have to click somewhere else (described in comment https://github.com/chameleon-system/chameleon-system/issues/509#issuecomment-581169288) Did I understand correctly from your comment https://github.com/chameleon-system/chameleon-system/issues/509#issuecomment-581947512 that this will be fixed later? That would be good, because it currently the behaviour is different from what I would expect.

- 7.0: The popup doesn't close at all, except when reloading the page.
