### ISSUE TITLE
Backend: Page settings cannot be shown if navigation entry has two connections

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#518]
**Describe the bug**

If a navigation entry has two page connections and one of them is invalid (empty) the page connected with the other valid connection cannot be shown in backend.

This is a bit arcane (invalid navigation page connection) but it is however rather easily achievable while working with the navigation.

Maybe wait for #107 and re-evaluate.

**Affected version(s)**
6.3+

**To Reproduce**
1. Create a page
2. Create a navigation tree node
3. Add two page connections - one of them empty = without linking to any page
4. Try to show the page settings page of the created page

**Technical details**
TreeNodeService::getByTreeId() is mostly the reason here: it will grab the first (and only one) navigation connection. However that one might be illegal or inactive. Called from \TCMSFieldPageTreeNode::getRenderedTreeNodePath().

**Comment by pixeljunkie** [comment]
Multiple page connections to one node is deprecated or should be. This feature is not usable since we switched to the symfony routing and this routing is unable to handle Routings based ion date/time settings made in the backend. So we should deprecate this feature now and remove it in a later version. This will make the handling easier with tree node connections. So i would not add any effort here to fix this and instead deprecate this.

**Comment by UlrichKu** [comment]
Desired solution: Doubled connections should not be supported to select anymore (mostly a gui change).
