### ISSUE TITLE
Autocomplete in search field selects no entry or too much (typeahead)

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#520]
**Describe the bug**
Introduced with #488:
Selecting the proposal in the autocomplete popup (typeahead) on a table page will sometimes do nothing (for "Pages" for example) or do too much:
Taken from #519: Pressing return in the search field might switch to the page's settings page - leaving "Navigation"

**Affected version(s)**
6.3.6+

**Technical details**
Typeahead's afterSelect (CHAMELEON.CORE.initializeEntryAutocomplete) does not have a notion of the action that might be defined on a table row.

**Comment by esono-anja** [comment]
Different things happen sometimes, but not always:

- You select a suggestion and the page settings are opened instead of "edit content". 

- If you use the Tab key instead of the mouse to select a suggestion, the entire list is displayed instead of the selected entry (if you use the mouse, you jump directly to the page). This happens when there are multiple pages for a text snippet. For example, type: "Bestell". Click with the mouse on "Bestellen" (the first entry) and you will get directly to the page. If you use Tab instead of the mouse, a list with all pages containing "Bestell" will be shown (as if you had pressed Enter). But sometimes the page will be displayed. 
Not sure what happens under which circumstances.
