### ISSUE TITLE
Sponsored Voucher was added and then directly removed

### ISSUE THREAD

**Issue by pSpeck** [chameleon-system/chameleon-system#540]
**Describe the bug**
If you add a sponsored voucher with a required minimum basket value to your basket, it could be that your voucher was added and the directly removed. During checking minimum basket value for sponsored vouchers the shipping costs are needed. On the Recalculate of none sponsored vouchers all voucher where checked if allowed or not.  But on checking none sponsored vouchers the basket has not set his shipping costs.  

**Affected version(s)**
6.2

**To Reproduce**
1. Add products to basket with a sum of 18€ and shipping cost of 3€ so you get higher then 20€
2. Then add a sponsored voucher with minimum basket amount of 20€
3. Shop shows message that voucher was added and removed.
4. Shop does not remove the voucher.

**Technical details**
RecalculateNoneSponsoredVouchers() does only check none sponsored vouchers.
and RecalculateVouchers() only sponsored vouchers. So we have the needed shipping cost on checking sponsored vouchers

**Comment by esono-anja** [comment]
Something still seems to be wrong here. The test with a sponsored voucher, as described above, works. But then I tried a non-sponsored voucher with a shopping cart that had not yet reached the minimum order value. The 6.2 and 6.3 crashed as a result (7-0 I have not tried yet, most likely it is the same).

1. create an unsponsored voucher with a minimum order value of 20€
2. put articles in the shopping cart that have an order value of less than 20€.
3. a message is displayed that the voucher cannot be redeemed because the minimum order value has not been reached
4. increase the shopping cart value accordingly to > 20€.
5. enter voucher name again
=> System crashes: 6-2 500 error; 6-3: service temporarily not available

**Comment by UlrichKu** [comment]
Now reverting this fix as it makes (other) things worse and a fix for that is not clear at the moment.

**Comment by UlrichKu** [comment]
Should be tested in this hotfix version: Wrong fix was added to the last version. It should now be removed again.

**Comment by esono-anja** [comment]
Test result: fix has been removed, original bugs occurs again
