### ISSUE TITLE
Backend: Portal>System page>Assign tree node: Levels are missing

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#567]
**Describe the bug**
Assigning a node for a system page will only show 5 levels. If the desired page is at level 6 of the navigation tree it cannot be selected.

(Note this kind of depth does not exist normally in the demo shop.)

**Affected version(s)**
6.3+ (since #107)

**Comment by UlrichKu** [comment]
It can also be noted here that selecting a node could directly close that popup.

At the moment however another click on "Confirm selection" is necessary.

Also the display of checkboxes in front of the entries is confusing as no multiple selection is possible here.

**Comment by ckleis** [comment]
Unfortunately I cannot reproduce the bug. I could assign a page from any level:
![Selection_047](https://user-images.githubusercontent.com/26296728/78373972-93ff1480-75cb-11ea-9a52-9128da771687.png)
![Selection_048](https://user-images.githubusercontent.com/26296728/78373992-995c5f00-75cb-11ea-81e6-01b42ccb8696.png)
Please test it again and describe it exactly.

We had discussed closing the popup directly after a selection click.
Thus, a wrong selection cannot be undone. And because you can assign a node across the entire width of the pop-up window, you easily could click on an unwanted selection.

The checkboxes before the nodes are set by jstree and in fact a muliple selection isn't possible here.

**Comment by UlrichKu** [comment]
Doesn't happen anymore for me either.
