### ISSUE TITLE
Backend: Changelog: Memory limit exceeded on save

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#617]
**Describe the bug**
For tables with an mlt connection to a table with lots of entries (for example shop_article) saving such an entry will show an error.
Internally it fails with an OutOfMemoryException.

**Affected version(s)**
6.1+ (fixed for 6.3+)

**Technical details**
\TCMSMLTField::getMltValues() might enumerate the whole target table (for "FindItemsWithProperty()") which then potentially does not fit in memory.

**Desired solution**
This "check target" in cms mode should be removed altogether.

**Comment by fabianbarth-esono** [comment]
The memory limit seems fine now, I can record changes in mlt tables. Also, mlt fields still seem to work.
But: When I change an mlt field that has a special name for the mlt table, for example when I add an accessory in the "Cross selling" tab of a product, and I click on the change, I get the following error:

![ChangeLogError](https://user-images.githubusercontent.com/17163435/97148640-c2ad2a00-176b-11eb-8245-be7781901f0f.png)

Ist this a problem introduced by the changes for this issue?

(The changelog does not work until https://github.com/chameleon-system/chameleon-system/issues/591 is fixed, because records cannot be inserted into change log table anymore. Tested with a temporarily fixed version)

**Comment by UlrichKu** [comment]
> Ist this a problem introduced by the changes for this issue?

Doesn't look like it.
This problem is probably there for some time.

Nevertheless I have prepared a fix for it.

**Comment by fabianbarth-esono** [comment]
Merged the fix. Will test again when deployed.
