### ISSUE TITLE
Backend: date field cannot be emptied

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#624]
**Describe the bug**
In any date field in the backend you cannot reset it to empty.

**Affected version(s)**
7.0 (fixed for)

**To Reproduce**
* Go to any data set with a date - an easy example is found for "Search > Shop search index status"
* Empty the content of a date field with the keyboard (click in it; mark everything; delete)
* Click Save
* Reload the page
-> the date field's contents are restored

**Technical details**
There will be an error in the javascript console. For example "moment.format is not a function"

**Comment by esono-anja** [comment]
The old date is not restored anymore, but todays date is filled in after reload. But I guess this behaviour is correct?

**Comment by pixeljunkie** [comment]
The problem seems not fixed using Firefox. If you empty the filled field by selecting the whole string with CTRL+A end DEL. The field seems to be empty, but the new empty value is not transfered to the hidden field. The change event does not trigger.

![Selection_999(500)](https://user-images.githubusercontent.com/958920/101335584-b1cafa80-3879-11eb-86b1-af340a58ec9c.png)

**Comment by UlrichKu** [comment]
Tempusdominus does not correctly trigger its change.datetimepicker event when only the DELETE key is used.

It works for example with the BACKSPACE key.

**Comment by fabianbarth-esono** [comment]
Successor for the open comment: https://github.com/chameleon-system/chameleon-system/issues/665

**Comment by fabianbarth-esono** [comment]
> The old date is not restored anymore, but todays date is filled in after reload. But I guess this behaviour is correct?

This is the desired behavior when the date picker is opened.
