### ISSUE TITLE
Can't save navigation tree order

### ISSUE THREAD

**Issue by FinnBrackrock** [chameleon-system/chameleon-system#627]
Once you click on the menu entry navigation and try to change the order via drag and drop, you will notice, that it works. Only temporarily though. Once you visit any other page, everything is resetted.
![Selection_012](https://user-images.githubusercontent.com/58431430/90518193-b8b4ec80-e166-11ea-8294-d314abb4d915.png)

So I looked for another way to change the order and found this button when looking through the Portale/Websites menu entry:
![Selection_013](https://user-images.githubusercontent.com/58431430/90518992-c1f28900-e167-11ea-9b6f-73fc6e995915.png)
This button makes no sense to me. If the functionality is to define a Portal, that gets selected in case multiple portals are placed on one domain and there is no identifier in the URL, why isn't it a field that defines one "main" portal. Why a sort button? However it appears that the button isn't even used in the chameleon base code anymore so it might as well be removed / hidden.

I noticed that the field "entry_sort" in the cms_tree table is ignored when it comes to the displayed tree structure. The red numbers are the actual position in the tree, the black numbers are those that are written to the database.
![Selection_015](https://user-images.githubusercontent.com/58431430/90538630-1a815080-e17f-11ea-9661-38ac8c382ea0.png)

The expected behavior would be, that the drag and drop function in the navigation section permanently saves the node order.

**Comment by fabianbarth-esono** [comment]
The problem is, that the first level below "Websites" is created by getting all portals and then using the "Navigation start node" to create the actual nodes. This means we need should re-order this level using the order from cms_tree after we loop through the portals. 

To see this behavior, the project needs to have multiple portals, which is a little tricky to do: https://github.com/chameleon-system/chameleon-system/issues/646
