### ISSUE TITLE
Some dependencies fixed on patch level

### ISSUE THREAD

**Issue by rnuernberg** [chameleon-system/chameleon-system#671]
**Describe the bug**

Some dependencies in 7.1 are specified including the patch level. This results in two problems:

- Projects migrating from 7.0 to 7.1 my have downgraded dependencies - which may result in unexpected behavior - or  even introduce security issues.
- If patch level dependencies are kept, then we are forced to release an update anytime a dependency releases a patch level update.

**Affected version(s)**
7.1.0

**Comment by UlrichKu** [comment]
Also other versions must be unfixed here:

For example fixing "doctrine/doctrine-bundle": "2.0.7" will lead to a logic error in \Doctrine\Bundle\DoctrineBundle\Command\Proxy\RunSqlDoctrineCommand which is fixed with 2.0.10.

(error: Symfony\Component\Console\Exception\LogicException: An option named "connection" already exists.)
