### ISSUE TITLE
less compile via console tries to include the new backend theme

### ISSUE THREAD

**Issue by pixeljunkie** [chameleon-system/chameleon-system#764]
**Describe the bug**
Since version 7.0.13 there is a theme for the backend that is handled like frontend themes (introduced with: https://github.com/chameleon-system/chameleon-system/issues/648). 
The problem is, that the backend theme snippet directory paths are loaded additionally to any frontend theme paths and added at the end of the snippet directory list, which overwrites theme paths. 
This problem only occurs if the LESS compile process is called via console:
```
./app/console chameleon_system:less:compile
```

In this case the compiler breaks with an error like:

```
Symfony\Component\Debug\Exception\ContextErrorException: Notice: Undefined property: Less_Parser::$furthest
```

Looking into the details with a debugger shows, that it is trying to load less files from paths in web/assets/less which do not exist.
Creating the files helps avoiding the crash, but means, that your files with the same name are never loaded, because the dummy files are loaded instead. This is because of the snippet directory chain order.

**Affected version(s)**
7.0.13/7.1.13

**To Reproduce**
1. Remove possible dummy files from web/assets/less directory
2. run: ./app/console chameleon_system:less:compile
3. See error or broken CSS output

**Expected behavior**
Frontend themes and the backend theme should never be mixed together.

**Comment by pixeljunkie** [comment]
The PR that introduced the issue: https://github.com/chameleon-system/chameleon-base/pull/536/files

**Comment by rnuernberg** [comment]
The issue here is, that the current solution adds backend less files to the theme when the theme is generated via console.

Instead, we should generate css for a frontend portal or for the backend, but never mix the two. 

Since the theming is currently tied very closely to the portal, I would suggest breaking it out into a new service. A service, that will give me the current theme. The service will be able to do this automatically for calls made to the backend or to a specific portal. 

For the command that pre-generates css for all portals (and which should also generate the css for the backend), we would need to refactor the whole css generating logic. To avoid this, I would propose that we use a bit of a hack.

We decorate the new theme provider service with a class that allows us to actively set the theme. The console command compiling the less files can use this decorator to actively set the theme to use when it loops through the portals - and again when it generates the theme for the backend.
