### ISSUE TITLE
Product variants: "Is the parent of the variant active" field is not always updated

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#83]
**Describe the bug**
If the stock of a variant is changed then the field "Is the parent of the variant active?" is sometimes not updated and thus the product in a category still shown or not shown.

**Affected version(s)**
\>=6.1

**To Reproduce**
1. Use a product with i.e. two variants (and stock > 0); cache should be off (dev mode)
2. Open a category page (in frontend) that shows that product
3. Set the stock for both variants to 0
4. Reload category page: product is not shown anymore (ok)
5. Set the stock for one variant back to 1 - use the save button of the product to save this
6. Reload category page: product is still no shown (wrong)
7. If you now save the main product then the field "Is the parent of the variant active?" is updated correctly (workaround)

**Expected behavior**
The "Automatically deactivate" settings in the connected Delivery status (Stock>Delivery status>Switch to record) should be used.

**Comment by esono-anja** [comment]
The described bug is fixed, the product disappears from the category page if the stock of variants drops to 0 (or vice versa). However, I have noticed that the function "Offer preorder at 0 stock", which can be set for the article, no longer applies if the article has variants (only works for articles without variants). I would expect that this funktion overrides the global stock setting "Automatically deactivate when stock = 0".
I'm not sure if this problem is related to the fix described in the ticket.

**Comment by esono-anja** [comment]
Update: The behaviour described in my last comment does not only affect 6.2.3, but also older versions. So I guess it has nothing to do with the original issue.

**Comment by umulmrum** [comment]
@esono-anja could you file a separate issue?

This issue looks resolved, so close :-)
