### ISSUE TITLE
New backend theme

### ISSUE THREAD

**Issue by umulmrum** [chameleon-system/chameleon-system#99]
**Describe the solution you'd like**
The backend theme is quite old and should be modernized.

**Possible solution (if any)**
- Maybe the free CoreUI theme is a good choice (http://coreui.io/).
- We want to keep icons for main menu items, but the used icon set should be changed to something more modern.
- We should also consider removing jQueryUI - I think only a small part of it is used, still it lies directly in the CoreBundle instead of being required by a package manager. Maybe the new theme brings components that can replace those we use from jQueryUI.

**Comment by umulmrum** [comment]
@pixeljunkie Could you - as a first step - evaluate CoreUI and check if it suits our needs and is technically OK (implementation quality, download sizes for users, performance, changeability, ...)?

**Comment by pixeljunkie** [comment]
After looking in detail into coreui i think this is a very good foundation for a fresh backend reboot. It is based on bootstrap4, so 90% of our current styling should already work, because wie use bootstrap3 already. Migration to bootstrap 4 is needed of course.
Another issue is the icon set. I would replace the famfamfam icon set with a clear black and white svg/icon font set. But this is not so easy, because we have really a lot of icons and all MIT or creative commons licenced icon sets i could found had not enough diversity. Even the Google Material icon set has mostly system related icons, like alerts, notifications, up, down clock. For example, you will not find any icon for sports (except a golf course icon). Maybe we should add an icon set, for the basics and allow importing another one via backend for user related special icon sets.

**Comment by pixeljunkie** [comment]
About jQueryUi... yes, we should remove it, because most of it is not used and was replaced by bootstrap components already, but i need to have a deeper look where it is used at the moment.

**Comment by esono-anja** [comment]
1. Lists are not responsive. Especially in long lists such as in products, you only see half of the line
=> concerns tablet mode
![tablet_listen](https://user-images.githubusercontent.com/15125103/53099991-3cb4f680-3527-11e9-9502-071a7f220e31.png)

2.  Menu item "navigation": The navigation items are not clickable, so you can neither create, edit or delete the navigation nor open submenu items with the plus sign.
In the desktop we have the right-click menu. How is this intended for tablet mode?
=> concerns tablet mode

**Comment by umulmrum** [comment]
1: Could you fix this @ckleis ?

2: I added this point to #107 - probably too much to squeeze in 6.3.0.
